version: '3'

vars:
  DEPLOY_DIR: '{{.ROOT_DIR}}/deploy'

tasks:
  ### BEGIN SECTION: Terraform shared utility tasks
  tf:init:
    desc: Common tf initialization task.
    requires: &necessary-tf-vars
      vars: [TF_PROJECT_DIR]
    dir: '{{.TF_PROJECT_DIR}}'
    cmds:
      - sops exec-env {{.DEPLOY_DIR}}/secrets.sops.env 'tofu init -backend-config={{.ROOT_DIR}}/backends/cloudflare-r2.conf {{.CLI_ARGS}}'
  tf:clean:
    desc: Common tf project cleaning task.
    dir: '{{.TF_PROJECT_DIR}}'
    requires: *necessary-tf-vars
    cmds:
      - rm -rf ./.terraform .terraform.lock.hcl
  tf:run:
    desc: Common tf project runner task.
    dir: '{{.TF_PROJECT_DIR}}'
    requires: *necessary-tf-vars
    cmds:
      - tofu {{.CLI_ARGS}}
  tf:*:
    desc: Common tf project runner task.
    dir: '{{.TF_PROJECT_DIR}}'
    requires: *necessary-tf-vars
    vars: &subcommand-passthrough-vars
      SUBCOMMAND: '{{index .MATCH 0}}'
    env:
      TF_VAR_tf_operation: "{{.SUBCOMMAND}}"
    cmds:
      - sops exec-env {{.DEPLOY_DIR}}/secrets.sops.env 'tofu {{.SUBCOMMAND}} {{.CLI_ARGS}}'
  ### END SECTION: Terraform shared utility tasks

  ### BEGIN SECTION: Terraform modules for cloudflare example stack
  cf:tf:init:
    desc: Initialize the cloudflare example stack Terraform module
    cmds:
      - task: tf:init
        vars:
          TF_PROJECT_DIR: "{{.ROOT_DIR}}/cf-example"
  cf:tf:clean:
    desc: Clean the cloudflare example stack Terraform module
    cmds:
      - task: tf:clean
        vars:
          TF_PROJECT_DIR: "{{.ROOT_DIR}}/cf-example"
  cf:tf:*:
    desc: Run a command in the cloudflare example stack Terraform module
    vars: *subcommand-passthrough-vars
    cmds:
      - task: tf:{{.SUBCOMMAND}}
        vars:
          TF_PROJECT_DIR: "{{.ROOT_DIR}}/cf-example"
  ### END SECTION: Terraform modules for cloudflare example stack